services:
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./data/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt

  recipe-loader:
    image: alpine:3.20.0
    container_name: recipe-loader
    depends_on:
      - elasticsearch
    volumes:
      - ./data/recipes_parsed.json:/recipes_parsed.json
      - ./data/init-elastic.sh:/init-elastic.sh
    entrypoint: [ "/bin/sh", "/init-elastic.sh" ]

  backend:
    build:
      context: app
    container_name: app
    ports:
      - "5050:5050"
    depends_on:
      - elasticsearch

volumes:
  esdata:
